benchmark: galaxies
method: npe
simulation_budgets: [10, 50, 100, 200, 500, 1000, 1400, 1800]
val_fraction: 0.1
train_set_size: 131072
val_set_size: 13110
test_set_size: 10000
coverage_set_size: 10000
block_size: 1000
seed: 1
nb_runs: 5
train_batch_size: [1, 4, 8, 8, 16, 16, 16, 32]
weight_decay: [0., 0., 0., 0., 0., 0., 0., 0.]
test_batch_size: 256
coverage_batch_size: 1024
epochs: 500
learning_rate: 1e-3
min_lr: 1e-5
nb_parallel_coverages: 1
experience_dir: results/npe/galaxies
data_path: data
diagnostics: ["coverage", "nominal_log_prob", "uncertainty"]
schedule: True
